spring:
  application:
    name: sse
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
server:
  port: 8899
